name = "cf-workers-audit-logs"
workers_dev = true
type = "javascript"

[triggers]
crons = ["* * * * *"]

# uncomment if you are deploying manually
kv_namespaces = [{binding="KV_AUDIT_LOGS", id="2b7a0ad6b8d14afbaee4c6cac756a416"}]
compatibility_date = "2022-11-30"
